sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "8"
  - "10"
  - "12"
install: npm install
script:
  - npm run validate
  - npm run test
branches:
  only: master
