sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: "10"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run validate
  - npm run codecov
branches:
  only: master
